apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shipment-service
  template:
    metadata:
      labels:
        app: shipment-service
    spec:
      containers:
      - name: shipment-service
        image: ificiency/shipment-service:latest
        ports:
        - containerPort: 5000
