#ConfigMap and Secret for storing configuration and sensitive data. Remember not to store sensitive data in ConfigMaps:

apiVersion: v1
kind: Secret
metadata:
  name: inventory-db-secret
type: Opaque
data:
  db_user: aWZpeWVtaQ0K
  db_password: YnJhY2V1cA0K
