#inventory-service-deployment.yaml for the Flask application:

apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
      - name: inventory-service
        image: ificiency/inventory-management:latest
        ports:
        - containerPort: 5000
        env:
          - name: FLASK_APP
            value: "app.py"
          - name: DATABASE_URL
            value: "mysql+pymysql://ifiyemi:braceup@inventory-db-service:3306/inventory_db"
