version: '3.8'

services:
  order_web:
    build: .
    ports:
      - "5001:5001"
    environment:
      - FLASK_RUN_PORT=5001
      - DATABASE_URL=mysql+pymysql://client:doctor@db:3306/order_db
    depends_on:
      - db

  db:
    image: mysql:5.7.44  # Specifying version for consistency
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=jesus
      - MYSQL_DATABASE=order_db
      - MYSQL_USER=client
      - MYSQL_PASSWORD=doctor
    ports:
      - "3308:3306"  # Change from 3307 to 3308
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
