apiVersion: v1
kind: Service
metadata:
  name: order-management-service
spec:
  selector:
    app: order-management-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
