apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-management-mysql-pvc  # Changed to user-management-mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
