apiVersion: v1
kind: Service
metadata:
  name: user-management-service  # Corrected to user-management-service
spec:
  selector:
    app: user-management-service  # Corrected to user-management-service
  ports:
  - protocol: TCP
    port: 80  # External port
    targetPort: 5000  # Internal port, where the Flask app is running
  type: LoadBalancer
